(MSVC, C++11) Add Network information(interface index, MAC, IPv4, Description)
lfreist/hwinfo pull request #65
Opened 2023-10-30 09:43 UTC by MRsoymilk

The information shows below:
![My Network Information](https://github.com/lfreist/hwinfo/assets/35524499/0eb85666-98d2-40e8-bb7d-e07108f7d75d)

2023-12-05 12:37 UTC, lfreist requested changes
Thank you for the contribution. All in all good work! Please address the issues stated in the comments so that I can merge your pull-request.

Also make sure that all files are in line with the coding style (.clang-format)

2023-12-05 12:37 UTC, lfreist commented on include/hwinfo/bios.h
Can you add dummy implementations for Linux (and OSX) for this classes member functions? They can just return "<unknown>" but they need to be implemented.

2023-12-05 12:37 UTC, lfreist commented on include/hwinfo/cpu.h
> +  const std::string& processorId() const;
Not sure if this information is useful at all. Maybe just remove it for the time being

2023-12-05 12:37 UTC, lfreist commented on include/hwinfo/network.h
> +// Copyright MRsoymilk
I cannot accept copyrighted content for this project

2023-12-05 12:37 UTC, lfreist commented on include/hwinfo/network.h
Could you add Linux (and maybe OSX) dummy implementations for this classes member functions too?

2023-12-05 12:37 UTC, lfreist commented on include/hwinfo/network.h
> +  HWI_NODISCARD const std::string& interfaceIndex() const;
The new HWinfo style is to return std::string instead of const std::string& because of copy elision

2023-12-05 12:37 UTC, lfreist commented on include/hwinfo/network.h
> +  std::string _ipv4{}, _ipv6{};
please write them in separate statements for readability

2023-12-05 12:37 UTC, lfreist commented on include/hwinfo/os.h
> +  HWI_NODISCARD std::string uuid() const;
Could you add Linux dummy implementations here too?

2023-12-05 12:37 UTC, lfreist commented on src/CMakeLists.txt
Once you have added the dummy implementations, you can add the linux and OSX cpp files here too

2023-12-05 12:37 UTC, lfreist commented on src/network.cpp
> +// Copyright MRsoymilk
I cannot accept Copyright code for this project

2023-12-11 03:39 UTC, MRsoymilk commented on include/hwinfo/bios.h
OK, I will try

2023-12-11 10:17 UTC, MRsoymilk commented
it seems a lot of things that need to be modified and it will take me some time to do

2024-10-14 13:33 UTC, closed without merging

2024-10-14 17:29 UTC, MRsoymilk commented
I am a time traveler from 3023. The spacecraft malfunction makes it impossible to modify...
Well, actually I put it on hold for a long time, I'm very sorry.